name: gooroo group
favicon: null
layout_spectrum: 0.32911446900106966
typography_spectrum: 0.5888
title: marketing solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7c44e'
    - '#818181'
    - '#666666'
    - '#000000'
    - '#808000'
  brandStrength: 0.8841460915282369
  lightness: 0.5
  saturation: 0.21309785172343254
  rhythmicContrast: 0
purpose: []
